### ISSUE TITLE
Ignore  prepare_zpool test on failure? 

### ISSUE THREAD

**Issue by jasonodoom** [ashuio/shavee#27] opened 2023-03-02 04:57 UTC
Hello, I am almost done with packaging Shavee for NixOS. However, I see [a unit test that needs root permission](https://github.com/ashuio/shavee/blob/master/shavee-bin/src/main.rs#L493). This isn't supported is there an alternative or can you ignore this specific test? 

```
error: test failed, to rerun pass `-p shavee --bin shavee`
error: builder for '/nix/store/nr969jrh81fln3j79ipbpkyhkx4f1wyd-shavee-0.5.drv' failed with exit code 101;
```

**Comment by kiavash-at-work** [comment] 2023-03-02 19:32
Hi @jasonodoom, I have updated PR #26 so the unit tests that depend on the root permission to gracefully exit in case the root permission is not granted, instead of causing a `panic` and fail the tests. Please give it a try and if resolves your issue, we can close this case after that PR is merged.

**Comment by jasonodoom** [comment] 2023-03-02 21:03
Thanks @kiavash-at-work  looks like that worked! Can you also do the same for `dataset_does_not_exists_test`? That one is failing too: 

```
failures:

---- zfs::tests::dataset_does_not_exists_test stdout ----
thread 'zfs::tests::dataset_does_not_exists_test' panicked at 'ZFS and ZPOOL tools must be installed. Test terminated early!: Os { code: 2, kind: NotFound, message: "No such file or directory" }', shavee-core/src/zfs.rs:451:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    zfs::tests::dataset_does_not_exists_test

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 431.3
```
Then you can re-package and I will build from that and if everything is fine from there (which it should be) I'll create a PR in nixpkgs.

**Comment by kiavash-at-work** [comment] 2023-03-02 21:45
I made the ZFS units test to exit gracefully too. Please check the updated code again.

**Comment by jasonodoom** [comment] 2023-03-02 22:56
Thanks @kiavash-at-work all tests are passing. Can you please tag this so I can work from it?

**Comment by kiavash-at-work** [comment] 2023-03-02 23:01
@ashuio as the maintainer of this repo can only generate a new tag/release after merging the PR.

**Comment by jasonodoom** [comment] 2023-03-02 23:06
noted. I will wait patiently then 😄

**Comment by ashuio** [comment] 2023-03-06 22:57
Sorry for the delay, the commit is merged and tagged.

**Comment by jasonodoom** [comment] 2023-03-06 23:41
no worries @ashuio thank you. It looks like the file hash test are now failing. Can you or @kiavash-at-work please resolve?

```
     > thread 'filehash::tests::get_filehash_unit_test' panicked at 'called `Result::unwrap_err()` on an `Ok` value: [114, 198, 213, 139, 67, 213, 120, 43, 163, 13, 255, 110, 191, 190, 203, 251, 149, 28, 124, 127, 251, 14, 155, 0, 181, 106, 178, 75, 235, 244, 197, 242, 51, 230, 184, 174, 82, 132, 6, 213, 33, 91, 98, 211, 223, 239, 228, 8, 236, 29, 70, 188, 168, 158, 241, 251, 66, 152, 199, 6, 79, 85, 98, 12]', shavee-core/src/filehash.rs:643:30
       >
       >
       > failures:
       >     filehash::tests::get_filehash_unit_test
       >     filehash::tests::remote_file_hash
       >
       > test result: FAILED. 11 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.19s
```

**Comment by kiavash-at-work** [comment] 2023-03-07 18:16
Hi @jasonodoom,

I am not able to duplicate this error. Can you please run these units tests using this command 
`$ cargo test --package shavee_core --lib -- filehash::tests --nocapture`
and share the output for our review?

**Comment by jasonodoom** [comment] 2023-03-07 21:19
Hi @kiavash-at-work This seems to be the issue: `thread 'filehash::tests::get_filehash_unit_test' panicked at 'called `Result::unwrap_err()` on an `Ok` value` 

In a local environment this error isn't present but for the case of nix packaging it appears. 

```
failures:

---- filehash::tests::get_filehash_unit_test stdout ----
0
1
2
3
4
thread 'filehash::tests::get_filehash_unit_test' panicked at 'called `Result::unwrap_err()` on an `Ok` value: [114, 198, 213, 139, 67, 213, 120, 43, 163, 13, 255, 110, 191, 190, 203, 251, 149, 28, 124, 127, 251, 14, 155, 0, 181, 106, 178, 75, 235, 244, 197, 242, 51, 230, 184, 174, 82, 132, 6, 213, 33, 91, 98, 211, 223, 239, 228, 8, 236, 29, 70, 188, 168, 158, 241, 251, 66, 152, 199, 6, 79, 85, 98, 12]', shavee-core/src/filehash.rs:643:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- filehash::tests::remote_file_hash stdout ----
0
thread 'filehash::tests::remote_file_hash' panicked at 'called `Result::unwrap_err()` on an `Ok` value: [114, 198, 213, 139, 67, 213, 120, 43, 163, 13, 255, 110, 191, 190, 203, 251, 149, 28, 124, 127, 251, 14, 155, 0, 181, 106, 178, 75, 235, 244, 197, 242, 51, 230, 184, 174, 82, 132, 6, 213, 33, 91, 98, 211, 223, 239, 228, 8, 236, 29, 70, 188, 168, 158, 241, 251, 66, 152, 199, 6, 79, 85, 98, 12]', shavee-core/src/filehash.rs:447:26


failures:
    filehash::tests::get_filehash_unit_test
    filehash::tests::remote_file_hash

test result: FAILED. 11 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.19s

error: test failed, to rerun pass `-p shavee_core --lib`
error: builder for '/nix/store/a8frqy4bf51wdy701pq3bdmp75sl3kn8-shavee-0.5.1.drv' failed with exit code 101;
       last 10 log lines:
       > thread 'filehash::tests::remote_file_hash' panicked at 'called `Result::unwrap_err()` on an `Ok` value: [114, 198, 213, 139, 67, 213, 120, 43, 163, 13, 255, 110, 191, 190, 203, 251, 149, 28, 124, 127, 251, 14, 155, 0, 181, 106, 178, 75, 235, 244, 197, 242, 51, 230, 184, 174, 82, 132, 6, 213, 33, 91, 98, 211, 223, 239, 228, 8, 236, 29, 70, 188, 168, 158, 241, 251, 66, 152, 199, 6, 79, 85, 98, 12]', shavee-core/src/filehash.rs:447:26
       >
       >
       > failures:
       >     filehash::tests::get_filehash_unit_test
       >     filehash::tests::remote_file_hash
       >
       > test result: FAILED. 11 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.19s
       >
       > error: test failed, to rerun pass `-p shavee_core --lib`
       For full logs, run 'nix log /nix/store/a8frqy4bf51wdy701pq3bdmp75sl3kn8-shavee-0.5.1.drv'.
```

**Comment by kiavash-at-work** [comment] 2023-03-07 21:35
> In a local environment this error isn't present but for the case of nix packaging it appears.

It seems that the packager doesn't allow `curl` to access the internet so the unit tests that depend on it fail.

I prefer not to remove these unit tests and instead have a condition in the unit test code that detects it is being run by nix packaging and skip the tests that depend on the internet. Is there any indication in the packager that can be passed to the unit test code (like ENV variable)?

**Comment by kiavash-at-work** [comment] 2023-03-07 22:31
Please give [this](https://github.com/kiavash-at-work/shavee) a try and it works in your build environment I will submit a PR. Otherwise, I need your help to fine tune the logic.

I added [this](https://github.com/kiavash-at-work/shavee/blob/99f290a10d84fd647cf966cd8f87d1c209785c04/shavee-core/src/filehash.rs#L317) to check for existence of `buildPhase` ENV variable to skip the test if it exists (its value is not checked).

``` rust
        // Check for Nix package builder before running the unit test [issue #27]
        if std::env::var("buildPhase").is_ok() {
            eprintln!("Nix package environment detected. Unit test is skipped.");
            return;
        }
```

**Comment by jasonodoom** [comment] 2023-03-08 03:49
@kiavash-at-work , thanks for working with me on this.  I was able to test it locally via `buildPhase = "echo";` Fingers crossed but it's passing and everything should be good to go. And of course with the removal of `buildPhase` the tests fail as expected. 

Can you update to check for the existence of `meta` instead? The current use of `buildPhase`  will probably receive scrutiny as it's not logical. 

```
running 3 tests
test args::tests::input_args_check ... ok
Dataset Password: test tests::password_mode_hash_test ... ok
Dataset Password: test tests::integration_tests ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s

     Running unittests src/lib.rs (target/x86_64-unknown-linux-gnu/release/deps/shavee_core-9fcc89409d48fbc9)

running 13 tests
test filehash::tests::get_filehash_unit_test ... ok
test filehash::tests::remote_file_hash ... ok
test tests::port_check_test ... ok
test zfs::tests::zfs_list_test ... ok
test tests::parse_file_size_arguments_test ... ok
test zfs::tests::zfs_create_load_unload_key_test ... ok
test zfs::tests::zfs_mount_umount_test ... ok
test zfs::tests::zfs_name_validation ... ok
test zfs::tests::zfs_to_string_test ... ok
test filehash::tests::local_file_hash ... ok
test zfs::tests::dataset_does_not_exists_test ... ok
test password::tests::test_hash_argon2 ... ok
test logic::tests::file_key_calculation_test ... ok

test result: ok. 13 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.20s

     Running unittests src/lib.rs (target/x86_64-unknown-linux-gnu/release/deps/shavee_pam-e0030c1c026ab0c3)

running 1 test
test args::tests::input_args_check ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests shavee_core

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Finished cargoCheckHook
checkPhase completed in 1 minutes 15 seconds
installing
Executing cargoInstallHook
Finished cargoInstallHook
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/6ka2dsm1x088w3mfyz1xa5mwclv3lh8m-shavee-0.5.1
strip is /nix/store/dkw46jgi8i0bq64cag95v4ywz6g9bnga-gcc-wrapper-11.3.0/bin/strip
patching script interpreter paths in /nix/store/6ka2dsm1x088w3mfyz1xa5mwclv3lh8m-shavee-0.5.1
checking for references to /build/ in /nix/store/6ka2dsm1x088w3mfyz1xa5mwclv3lh8m-shavee-0.5.1...
/nix/store/6ka2dsm1x088w3mfyz1xa5mwclv3lh8m-shavee-0.5.1
```

**Comment by kiavash-at-work** [comment] 2023-03-08 17:51
This is very good that we found out the root cause of the test failures (lack of access to the internet by the builder). However it is not clear to me your proposed usage of `meta`.

Would you mind putting together your proposed solution as a simple algorithm (in any language that you prefer, even `bash` is ok) and I will try to write it in `Rust`?

**Comment by jasonodoom** [comment] 2023-03-08 20:13
>Unfortunately, I am not familiar with the Nix packager. Are any of these meta attributes exposed to the shell environment?
No worries, I am still new to this myself and wanted to learn more that's why I wanted to contribute to Nix packages.

Not unless you use `nix-env` 
But all of the phases such as `postInstall` and `buildPhase` are  exposed via stdenv
```
[nix-shell:~/code/shavee-dev]$ echo $postInstall
cp target/release/shavee $out/bin/ cp target/release/libshavee_pam.so $out/lib/security/libshavee_pam.so
```

>Regarding postInstall, I don't know how it is exposed to the unit tests of the rust code. Is it a package builder directive or shell environment set during the package build? 
It's exposed via the standard build environment (see above). 

The below is the current `postInstall` which executes these instructions after compilation. In this case the binary and  the library file are being copied to their necessary paths.

I am not using  `buildPhase` but  `postInstall` Your addition worked when I tested it but should be replaced with `posInstall`:

```
    // Check for Nix package builder before running the unit test [issue #27]
        if std::env::var("postInstall").is_ok() {
            eprintln!("Nix package environment detected. Unit test is skipped.");
            return;
        }
```
There doesn't need to be any additional steps besides that. No additional logic on the package itself is necessary and would be wasteful. Essentially, an environment is created, the source is pulled and the package is built within that environment. So we can expect everything to work as `postInstall` is also accessible and in use since it's necessary here to copy the binary after compilation.  

I tested with `buildPhase` and not `postInstall` to avoid the copying of the binary. 

If you prefer, you can also run this on your end:
```
# default.nix
with import <nixpkgs> { };

rustPlatform.buildRustPackage rec {
  pname = "shavee";
  version = "0.5.1";
  src = ./shavee;

  cargoSha256 = "sha256-iNGn5KknSNgazFSu6Nur7AkKVb6qKMxuFwTdCz5djWU=";

  nativeBuildInputs = [
    pkg-config
  ];  

  buildInputs = [
      libiconv
      linux-pam  
      makeWrapper
      openssl 
      openssl.dev

  ];

buildPhase = ''
  echo
'';


  meta = with lib; {
    description = "A Program to automatically decrypt and mount ZFS datasets using Yubikey HMAC as 2FA or any File on USB/SFTP/HTTPS.";
    homepage = "https://github.com/ashuio/shavee";
    license = licenses.mit;

    maintainers = with maintainers; [jasonodoom];
  };
}

```
Just run `nix-build`

**Comment by kiavash-at-work** [comment] 2023-03-08 21:08
Thank you for the complete and detailed description. The [change](https://github.com/kiavash-at-work/shavee/commit/9e99bebff398c94772ab607b84b4cb415b6a76a9) was simple. If this looks good to you, I will submit a PR.

**Comment by jasonodoom** [comment] 2023-03-09 00:04
LGTM, thanks so much! Please don't forget to do the same for `get_filehash_unit_test`

**Comment by ashuio** [comment] 2023-03-09 06:25
@jasonodoom i have merged the solution and created a new release, I have changed the tag name form `0.5.1` to `v0.5.1` so you might want to edit that on your end too.

Let me know if this works for you and I can close this issue.

**Comment by ashuio** [comment] 2023-03-10 15:20
@jasonodoom No worries, I updated it, can you check and let me know?

**Comment by jasonodoom** [comment] 2023-03-10 15:49
@ashuio good to go, thanks! The rest is up to me.

**Closed** 2023-03-10 15:53 UTC
